---
# tasks file for install-nginx
- name: Обновление всех пакетов
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes


- name: add filebeat group
  ansible.builtin.group:
    name: "{{ filebeat_group }}"
    state: present

- name: add filebeat user
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    shell: /bin/sh
    password: "*"
    group: "{{ filebeat_group }}"
#
#- name: Ensure nginx log directory exists
#  file:
#    path: "{{ nginx_log_dir }}"
#    state: directory
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_user }}"
#    mode: '0755'

- name: Configure Nginx logging
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

#- name: Set permissions on existing nginx log files
#  file:
#    path: "{{ item }}"
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_user }}"
#    mode: '0644'
#  with_items:
#    - "{{ nginx_log_dir }}/{{ nginx_access_log_file }}"
#    - "{{ nginx_log_dir }}/{{ nginx_error_log_file }}"


- name: Создание директории для SSL сертификатов
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Генерация самоподписанного сертификата
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/selfsigned.key -out /etc/nginx/ssl/selfsigned.crt -subj "/CN={{ domain }}"

- name: Копирование конфигурационного файла Nginx
  template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf
    owner: root
    group: root
    mode: '0644'

- name: Запуск и включение Nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes