---
- name: Disable UFW firewall
  become: yes
  service:
    name: ufw
    state: stopped
  when: ansible_service_mgr == 'systemd'

- name: Ensure UFW is disabled on boot
  become: yes
  service:
    name: ufw
    enabled: no
  when: ansible_service_mgr == 'systemd'

- name: Add PostgreSQL repository key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present


- name: Add PostgreSQL repository
  become: yes
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
    state: present
    update_cache: yes

- name: Install PostgreSQL 14 server
  become: yes
  apt:
    name: postgresql-14
    state: present
    update_cache: yes

- name: Check if PostgreSQL is initialized
  become: yes
  stat:
    path: /var/lib/postgresql/14/main/pg_stat
  register: stat_result

- name: Initialize PostgreSQL
  become: yes
  command: sudo -u postgres /usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main
  when: not stat_result.stat.exists

- name: Start and enable PostgreSQL service
  become: yes
  service:
    name: postgresql
    state: started
    enabled: yes
