---


- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: Download Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
    keyring: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Обновление всех пакетов
  apt:
    update_cache: yes

- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Copy Grafana datasource configuration
  template:
    src: grafana_datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yml
  notify: Restart Grafana

#- name: Create directory for Alertmanager configuration
#  file:
#    path: /etc/alertmanager
#    state: directory
#    mode: '0755'


#- name: Copy Alertmanager configuration
#  copy:
#    src: alertmanager.yml
#    dest: /etc/alertmanager/alertmanager.yml
#  notify: Restart Alertmanager

- name: Enable and start Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Enable and start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

#- name: Enable and start Alertmanager
#  service:
#    name: alertmanager
#    state: started
#    enabled: yes
