---
- name: Create Prometheus  group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present

- name: Create Prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    create_home: false
    shell: /sbin/nologin
    state: present
# https://github.com/prometheus/prometheus/releases/download/v2.45.5/prometheus-2.45.5.linux-amd64.tar.gz
- name: Download Prometheus

  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: '0755'

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes


- name: Install Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "{{ prometheus_install_dir }}/prometheus"
    mode: '0755'
    remote_src: yes


- name: Create Prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: '0644'


- name: Create systemd service file for Prometheus
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus
      Documentation=https://prometheus.io/docs/introduction/overview/
      Wants=network-online.target
      After=network-online.target
      
      [Service]
      User={{ prometheus_user }}
      Group={{ prometheus_group }}
      Type=simple
      ExecStart={{ prometheus_install_dir }}/prometheus \
        --config.file={{ prometheus_config_dir }}/prometheus.yml \
        --storage.tsdb.path={{ prometheus_data_dir }} \
        --web.console.templates={{ prometheus_install_dir }}/consoles \
        --web.console.libraries={{ prometheus_install_dir }}/console_libraries
      ExecReload=/bin/kill -HUP $MAINPID
      Restart=on-failure
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/{{ prometheus_service }}.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Prometheus

